name: "Bump version"
description: 'Bumps version'
inputs:
  actor:
    description: 'actor'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git config user.name "${{ inputs.actor }}"
        git config user.email "${{ inputs.actor}}@users.noreply.github.com"
        npx lerna version --yes --loglevel silly
        git status
      shell: bash